### ISSUE TITLE
zenstates.py msr module not loaded

### ISSUE THREAD

**Issue by ifrguy** [r4m0n/ZenStates-Linux#17]
Running zenstates.py generates the following trace back no matter what option selected:

> meg@amon:ZenStates-Linux-master> ./zenstates.py --c6-disable
Traceback (most recent call last):
  File "./zenstates.py", line 112, in <module>
    writemsr(0xC0010292, readmsr(0xC0010292) & ~(1 << 32))
  File "./zenstates.py", line 33, in readmsr
    raise OSError("msr module not loaded (run modprobe msr)")
OSError: msr module not loaded (run modprobe msr)

Module msr is most certainly loaded:

> > lsmod|grep msr
msr                    16384  0

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

Kernel version: 4.15.0-153
Python version: 3.6.9

Processor info:

> processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 1
model name	: AMD Ryzen 5 1600 Six-Core Processor
stepping	: 1
microcode	: 0x8001126
cpu MHz		: 1374.637

**Comment by ifrguy** [comment]
Please ignore previous report.  Seems to be working now.  My bad.  I'll see if this helps with the random frequent lock-ups.
