### ISSUE TITLE
MSR module not loaded error during Locking TSC Frequency

### ISSUE THREAD

**Issue by Road-Drum** [r4m0n/ZenStates-Linux#7]
As per workaround in #6 I have been able to list the frequencies correctly. However, on setting the P-States, the error that supposed been rectified still occurs. Log below:

`$ sudo /usr/bin/python3.6 ./zenstates.py -p 0 -f 73 -d A -v 35`
`Current P0: Enabled - FID = 64 - DID = A - VID = 35 - Ratio = 20.00 - vCore = 1.21875`
`Setting FID to 73`
`Setting DID to A`
`Setting VID to 35`
`Locking TSC frequency`
`Traceback (most recent call last):`
` File "./zenstates.py", line 103, in <module>`
`    writemsr(0xC0010015, readmsr(0xC0010015, c) | (1 << 21), c)`
` File "./zenstates.py", line 24, in writemsr`
`    raise OSError("msr module not loaded (run modprobe msr)")`
`OSError: msr module not loaded (run modprobe msr)`

At this point I'm pretty sure that there is no more issues but nonetheless this occurs. System:

Acer Nitro 5 AN515-42-R8SH
Ryzen 5 2500U with Vega Mobile Gfx

**Comment by kdb424** [comment]
Have you run this command as it indicated? Seems like user error.
```sudo modprobe msr```
